/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bdkserverside.jvm

import org.junit.Assert.assertNotNull
import org.junit.Test

class AppTest {
    
    @Test
    fun testWalletHasAddress() {
        val address = MiniWallet.newAddress()
        assertNotNull("app should generate an address", address)
    }
}
